# Production values for database-schema
replicaCount: 2

image:
  repository: prodtradingbotregistry.azurecr.io/database-schema
  pullPolicy: Always
  tag: "latest"

# Production database configuration
database:
  host: prod-postgresql
  port: 5432
  name: trading_platform_prod
  user: trading_platform
  existingSecret: "postgresql-credentials"
  existingSecretKey: password

# Production migration configuration
migration:
  enabled: true
  schedule: "0 3 * * 0" # Weekly at 3 AM Sunday (production maintenance window)
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 5
  activeDeadlineSeconds: 7200 # 2 hours for production migrations
  backoffLimit: 2 # More conservative retry policy in production
  restartPolicy: OnFailure

# Production resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Production monitoring and health checks
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Production security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  fsGroup: 1001

# Production node selection
nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - database-schema
        topologyKey: kubernetes.io/hostname
